[package]
name = "sc-dex-rewards-lock-abi"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.sc-dex-rewards-lock]
path = ".."

[dependencies.elrond-wasm]
version = "0.15.0"

[dependencies.elrond-wasm-debug]
version = "0.15.0"
